name: sipsorcery-core-win

on:
  push:
    branches:
      - master
      - fixtests
      
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x', '5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sipsorcery Windows
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Unit tests
      #run: dotnet test src/SIPSorcery.sln --framework netcoreapp3.1 -c Release --filter "Category!=IPv6&Category!=transport&Category!=txintegration"
      #run: dotnet test src/SIPSorcery.sln --framework netcoreapp3.1 -c Release
      #run: dotnet test test/unit/SIPSorcery.UnitTests.csproj --framework netcoreapp3.1
      run: dotnet test test/unit/SIPSorcery.UnitTests.csproj
